### ISSUE TITLE
frame rate

### ISSUE THREAD

**Issue by z2oh** [z2oh/MegaManClone#5]
do we want to lock frame rate (at 60 fps I'm guessing) or do we want to allow variable frame rates? there are benefits to both, but it is definitely 'easier' to have a locked frame rate

**Comment by lewaxml** [comment]
Since we are using update to handle the physics/movement calculations, I think we should keep it fixed, otherwise any changes in frame rate will change the way that any movement more complex that a strait line to have slight errors unless we control everything directly through position (which is more difficult)

**Comment by z2oh** [comment]
Okay I think fixed frame rate makes sense. It is easier and our game won't be graphically intensive enough to cause any modern machine to dip in fps. Let's still allow for variable framerate, but just assume it is constant. We can have some global property that is the frame rate lock.
